### PR TITLE
update

### PR DESCRIPTION
**Pull request by Livedox**
Now this is the npm package
No bugs when resizing
Multiple use
No background

### CODE REVIEW

**Comment by l1ve4code** [comment]
Hi! Thank you for your pull request! Can you tell me how to launch the project, please.

**Comment by Livedox** [comment]
npm run dev - for start
npm run build - for minified version

Just open the html in a browser

**Comment by Livedox** [comment]
*npm install

**Comment by l1ve4code** [comment]
Thanks! I'll merge it later.

**Comment by Livedox** [comment]
npm run watch 

http://localhost:8080/example/
http://localhost:8080/example/many.html

**Pull request merged**
